@startuml
title GoF Pattern : Observer + Memento

note as GoFLabel
  **<<Observer + Memento>>**
end note

class Document {
  + content: String
  + createMemento(): Memento
  + restore(Memento):  void
}
interface Toolbar {
  - update(): void
}
interface StatusBar {
  - update(): void
}
interface PreviewPanel {
  - update(): void
}
class DocumentObserver {
  + attach(): void
  + detach(): void
  + notify():  void
}

Document --> Toolbar
Document --> StatusBar
Document --> PreviewPanel
DocumentObserver *--> Document
GoFLabel .. Document
@enduml