@startuml
title GoF Pattern : Memento + Observer

note as GoFLabel
  **<<Memento + Observer>>**
end note

class Document {
  + id: int
  + content: string
  + save(): void
}
interface Memento {
  - restore(Document): void
}
class DocumentMemento {
  + document: Document
}
interface DocumentObserver {
  - update(Document): void
}
class Toolbar {
}
class StatusBar {
}
class PreviewPanel {
}

Document --> Memento
Document ..> DocumentObserver
DocumentMemento --|> Memento
Toolbar --> Document
StatusBar --> Document
PreviewPanel --> Document
GoFLabel .. Document
@enduml